const dishes=[
  {name:'Warm sourdough, cultured butter',description:'Maldon salt · garden herbs',price:6,category:'small',tags:['V'],detail:'Our overnight sourdough is served warm with cultured butter whipped with herbs from the garden.'},
  {name:'Heritage beetroot',description:'Goat curd · hazelnut · sorrel',price:11,category:'small',tags:['V','GF'],detail:'Roasted and pickled heritage beetroot with fresh goat curd, toasted hazelnut, and young sorrel.'},
  {name:'Cured chalk stream trout',description:'Cucumber · dill · buttermilk',price:14,category:'small',tags:['GF'],detail:'Lightly cured trout from Hampshire with compressed cucumber, dill oil, and cultured buttermilk.'},
  {name:'Market fish',description:'Leek · mussel · cider',price:25,category:'large',tags:['GF'],detail:'The best fish from today’s market with charred leek, mussels, and a light Yorkshire cider sauce.'},
  {name:'Roast squash',description:'Spelt · sage · smoked almond',price:21,category:'large',tags:['VG'],detail:'Slow-roasted squash, nutty spelt, crisp sage, and smoked almond cream.'},
  {name:'Yorkshire lamb',description:'Hispi cabbage · anchovy · mint',price:28,category:'large',tags:['GF'],detail:'Yorkshire lamb cooked over coals with buttered hispi cabbage, anchovy, and fresh mint.'},
  {name:'Set custard',description:'Rhubarb · oat · meadowsweet',price:10,category:'sweet',tags:['V'],detail:'Silky baked custard with Yorkshire rhubarb, toasted oat, and fragrant meadowsweet.'},
  {name:'Dark chocolate tart',description:'Crème fraîche · sea salt',price:11,category:'sweet',tags:['V'],detail:'Deep cocoa tart with cool crème fraîche and just enough sea salt.'},
  {name:'British cheese',description:'Seasonal chutney · crackers',price:13,category:'sweet',tags:['V'],detail:'A changing selection of British farmhouse cheese with house chutney and seeded crackers.'}
];
let activeFilter='all';let selectedTime='';let lastReservation=null;
const dishList=document.getElementById('dishes');
const booking=document.getElementById('booking');
const dishDialog=document.getElementById('dish-dialog');
const dateInput=document.getElementById('date');

function safe(value){const node=document.createElement('span');node.textContent=String(value??'');return node.innerHTML;}
function toast(message){const el=document.getElementById('toast');el.textContent=message;el.classList.add('show');clearTimeout(toast.timer);toast.timer=setTimeout(()=>el.classList.remove('show'),2200);}
function renderDishes(){const query=document.getElementById('menu-search').value.trim().toLowerCase();const visible=dishes.filter(dish=>(activeFilter==='all'||dish.category===activeFilter)&&(!query||`${dish.name} ${dish.description}`.toLowerCase().includes(query)));dishList.innerHTML=visible.length?visible.map(dish=>`<article class="dish"><button data-dish="${dishes.indexOf(dish)}"><div><h3>${safe(dish.name)}</h3><p>${safe(dish.description)}</p><div class="dish-tags">${dish.tags.map(tag=>`<span>${tag}</span>`).join('')}</div></div><b>£${dish.price}</b></button></article>`).join(''):'<p>No dishes match that search. Try another ingredient.</p>';}
document.querySelectorAll('[data-filter]').forEach(button=>button.onclick=()=>{document.querySelectorAll('[data-filter]').forEach(item=>item.classList.remove('active'));button.classList.add('active');activeFilter=button.dataset.filter;renderDishes();});
document.getElementById('menu-search').oninput=renderDishes;
dishList.onclick=event=>{const button=event.target.closest('[data-dish]');if(!button)return;const dish=dishes[Number(button.dataset.dish)];document.getElementById('dish-category').textContent=`${dish.category.toUpperCase()} PLATE`;document.getElementById('dish-name').textContent=dish.name;document.getElementById('dish-description').textContent=dish.detail;document.getElementById('dish-tags').innerHTML=dish.tags.map(tag=>`<span>${tag==='V'?'Vegetarian':tag==='VG'?'Vegan':'Gluten free'}</span>`).join('');document.getElementById('dish-price').textContent=`£${dish.price}`;dishDialog.showModal();};
document.getElementById('close-dish').onclick=()=>dishDialog.close();

const today=new Date();const tomorrow=new Date(today.getTime()+86400000);const maxDate=new Date(today.getTime()+90*86400000);dateInput.min=today.toISOString().split('T')[0];dateInput.max=maxDate.toISOString().split('T')[0];dateInput.value=tomorrow.toISOString().split('T')[0];
function renderTimes(){selectedTime='';document.getElementById('time').value='';const dateSeed=[...dateInput.value].reduce((sum,char)=>sum+char.charCodeAt(0),0)+Number(document.getElementById('party').value);const times=['12:00','12:30','13:00','13:30','17:30','18:00','18:30','19:00','19:30','20:00','20:30'];document.getElementById('time-slots').innerHTML=times.map((time,index)=>`<button type="button" ${((dateSeed+index*3)%7===0||Number(document.getElementById('party').value)>=7&&index%3===0)?'disabled':''}>${time}</button>`).join('');}
document.getElementById('time-slots').onclick=event=>{const button=event.target.closest('button:not(:disabled)');if(!button)return;document.querySelectorAll('#time-slots button').forEach(item=>item.classList.remove('selected'));button.classList.add('selected');selectedTime=button.textContent;document.getElementById('time').value=selectedTime;};
dateInput.onchange=renderTimes;document.getElementById('party').onchange=renderTimes;
function openBooking(){if(dishDialog.open)dishDialog.close();document.getElementById('booking-form').hidden=false;document.getElementById('confirmation').hidden=true;renderTimes();booking.showModal();}
document.addEventListener('click',event=>{if(event.target.closest('[data-book]'))openBooking();});
document.querySelector('.close').onclick=()=>booking.close();document.getElementById('done').onclick=()=>booking.close();
document.getElementById('booking-form').onsubmit=event=>{event.preventDefault();if(!selectedTime){toast('Please choose an available time');document.getElementById('time-slots').scrollIntoView({behavior:'smooth',block:'center'});return;}const code=`TT-${Math.random().toString(36).slice(2,7).toUpperCase()}`;lastReservation={name:document.getElementById('name').value.trim(),date:dateInput.value,time:selectedTime,party:document.getElementById('party').value,email:document.getElementById('email').value.trim(),occasion:document.getElementById('occasion').value,requests:document.getElementById('requests').value.trim(),code};const saved=JSON.parse(localStorage.getItem('table-thyme-bookings-v3')||'[]');saved.push(lastReservation);localStorage.setItem('table-thyme-bookings-v3',JSON.stringify(saved.slice(-10)));event.target.hidden=true;document.getElementById('confirmation').hidden=false;document.getElementById('confirmation-copy').textContent=`Thank you, ${lastReservation.name}. Your demo table for ${lastReservation.party} ${Number(lastReservation.party)===1?'guest':'guests'} is saved for ${new Date(lastReservation.date+'T12:00').toLocaleDateString(undefined,{weekday:'long',day:'numeric',month:'long'})} at ${lastReservation.time}.`;document.getElementById('booking-code').textContent=code;};
document.getElementById('download-booking').onclick=()=>{if(!lastReservation)return;const details=`TABLE & THYME — DEMO RESERVATION\n\nReference: ${lastReservation.code}\nName: ${lastReservation.name}\nDate: ${lastReservation.date}\nTime: ${lastReservation.time}\nParty: ${lastReservation.party}\nOccasion: ${lastReservation.occasion}\nRequests: ${lastReservation.requests||'None'}\n\nThis is a portfolio demonstration and not a real restaurant booking.`;const link=document.createElement('a');link.href=URL.createObjectURL(new Blob([details],{type:'text/plain'}));link.download=`table-thyme-${lastReservation.code}.txt`;link.click();setTimeout(()=>URL.revokeObjectURL(link.href),0);toast('Reservation details downloaded');};

const menuToggle=document.querySelector('.menu-toggle');const nav=document.getElementById('site-nav');menuToggle.onclick=()=>{const open=menuToggle.getAttribute('aria-expanded')==='true';menuToggle.setAttribute('aria-expanded',String(!open));nav.classList.toggle('open',!open);};document.querySelectorAll('#site-nav a').forEach(link=>link.onclick=()=>{nav.classList.remove('open');menuToggle.setAttribute('aria-expanded','false');});
document.getElementById('newsletter-form').onsubmit=event=>{event.preventDefault();localStorage.setItem('table-thyme-newsletter',document.getElementById('newsletter-email').value.trim());event.target.reset();toast('You’re on the demo seasonal list');};
document.getElementById('year').textContent=new Date().getFullYear();
renderTimes();renderDishes();
