const STORAGE_KEY='stockroom-workspace-v3';
const defaults={items:[
  {id:'keyboard',name:'Wireless keyboard',sku:'KEY-104',category:'Electronics',price:34.99,qty:18,threshold:5},
  {id:'notebook',name:'Recycled notebook',sku:'NOTE-28',category:'Office',price:6.5,qty:4,threshold:8},
  {id:'hub',name:'USB-C hub',sku:'HUB-210',category:'Electronics',price:42,qty:11,threshold:4},
  {id:'boxes',name:'Mailing boxes',sku:'BOX-050',category:'Packaging',price:1.25,qty:62,threshold:20},
  {id:'stand',name:'Laptop stand',sku:'STAND-3',category:'Accessories',price:27.5,qty:3,threshold:5},
  {id:'mouse',name:'Ergonomic mouse',sku:'MSE-112',category:'Accessories',price:22.9,qty:0,threshold:6}
],movements:[
  {id:'m1',itemId:'keyboard',product:'Wireless keyboard',type:'receipt',qty:8,note:'PO-1042 received',time:new Date(Date.now()-38*60000).toISOString()},
  {id:'m2',itemId:'notebook',product:'Recycled notebook',type:'sale',qty:3,note:'Online order #318',time:new Date(Date.now()-95*60000).toISOString()},
  {id:'m3',itemId:'boxes',product:'Mailing boxes',type:'receipt',qty:40,note:'Packaging delivery',time:new Date(Date.now()-26*3600000).toISOString()}
]};
let state=loadState();
const tbody=document.getElementById('inventory');const itemDialog=document.getElementById('item-dialog');const movementDialog=document.getElementById('movement-dialog');
function cloneDefaults(){return JSON.parse(JSON.stringify(defaults));}function loadState(){try{return JSON.parse(localStorage.getItem(STORAGE_KEY))||cloneDefaults();}catch{return cloneDefaults();}}function save(){localStorage.setItem(STORAGE_KEY,JSON.stringify(state));}function safe(value){const node=document.createElement('span');node.textContent=String(value??'');return node.innerHTML;}function uid(prefix){return`${prefix}-${Date.now()}-${Math.random().toString(36).slice(2,6)}`;}function money(value){return value.toLocaleString('en-GB',{style:'currency',currency:'GBP',minimumFractionDigits:2,maximumFractionDigits:2});}function toast(message){const el=document.getElementById('toast');el.textContent=message;el.classList.add('show');clearTimeout(toast.timer);toast.timer=setTimeout(()=>el.classList.remove('show'),2100);}function statusOf(item){return item.qty===0?'out':item.qty<=item.threshold?'low':'healthy';}function timeAgo(iso){const mins=Math.max(0,Math.round((Date.now()-new Date(iso).getTime())/60000));if(mins<1)return'Just now';if(mins<60)return`${mins} min ago`;if(mins<1440)return`${Math.round(mins/60)} hr ago`;return new Date(iso).toLocaleDateString();}
function visibleItems(){const query=document.getElementById('search').value.trim().toLowerCase(),category=document.getElementById('category').value,status=document.getElementById('status').value,sort=document.getElementById('sort').value;const items=state.items.filter(item=>(!query||`${item.name} ${item.sku}`.toLowerCase().includes(query))&&(category==='all'||item.category===category)&&(status==='all'||statusOf(item)===status));items.sort((a,b)=>sort==='qty-asc'?a.qty-b.qty:sort==='qty-desc'?b.qty-a.qty:sort==='value-desc'?b.qty*b.price-a.qty*a.price:a.name.localeCompare(b.name));return items;}
function renderInventory(){const items=visibleItems();tbody.innerHTML=items.length?items.map(item=>`<tr><td><div class="product"><i>${safe(item.name[0])}</i><div><b>${safe(item.name)}</b><small>Alert at ${item.threshold} units</small></div></div></td><td>${safe(item.sku)}</td><td>${safe(item.category)}</td><td>${money(item.price)}</td><td><div class="qty"><button data-quick="minus" data-id="${item.id}" aria-label="Remove one ${safe(item.name)}">−</button><b>${item.qty}</b><button data-quick="plus" data-id="${item.id}" aria-label="Add one ${safe(item.name)}">+</button></div></td><td><span class="badge ${statusOf(item)}">${statusOf(item)==='out'?'Out of stock':statusOf(item)==='low'?'Low stock':'Healthy'}</span></td><td>${money(item.price*item.qty)}</td><td><div class="row-actions"><button data-edit="${item.id}" aria-label="Edit ${safe(item.name)}">✎</button><button class="delete" data-delete="${item.id}" aria-label="Delete ${safe(item.name)}">×</button></div></td></tr>`).join(''):'<tr><td colspan="8" class="empty">No products match these filters.</td></tr>';document.getElementById('result-count').textContent=`${items.length} product${items.length===1?'':'s'}`;}
function renderMetrics(){const low=state.items.filter(item=>statusOf(item)==='low').length,out=state.items.filter(item=>statusOf(item)==='out').length,total=state.items.reduce((sum,item)=>sum+item.price*item.qty,0),units=state.items.reduce((sum,item)=>sum+item.qty,0);document.getElementById('total-products').textContent=state.items.length;document.getElementById('low-count').textContent=low+out;document.getElementById('stock-value').textContent=money(total).replace('.00','');document.getElementById('unit-count').textContent=units;document.getElementById('unit-change').textContent=`Across ${state.items.length} products`;}
function renderMovements(){document.getElementById('movement-list').innerHTML=state.movements.length?state.movements.slice(0,8).map(movement=>`<div class="movement ${movement.type==='sale'?'out':''}"><i>${movement.type==='receipt'?'↓':movement.type==='sale'?'↑':'±'}</i><div><b>${safe(movement.product)}</b><p>${safe(movement.note||({receipt:'Stock received',sale:'Sale / dispatch',adjustment:'Manual adjustment'}[movement.type]))}</p><time>${timeAgo(movement.time)}</time></div><span>${movement.type==='receipt'?'+':movement.type==='sale'?'-':'='}${movement.qty}</span></div>`).join(''):'<div class="empty">No stock movements recorded.</div>';const alerts=state.items.filter(item=>statusOf(item)!=='healthy').sort((a,b)=>a.qty-b.qty);document.getElementById('alert-list').innerHTML=alerts.length?alerts.map(item=>`<div class="alert"><i>!</i><div><b>${safe(item.name)}</b><p>${item.qty} on hand · alert at ${item.threshold}</p></div><button data-restock="${item.id}">Restock</button></div>`).join(''):'<div class="empty">Every product is above its alert level.</div>';}
function renderReports(){const categories=['Accessories','Office','Electronics','Packaging'];const values=categories.map(category=>({category,value:state.items.filter(item=>item.category===category).reduce((sum,item)=>sum+item.price*item.qty,0)}));const max=Math.max(1,...values.map(item=>item.value));document.getElementById('category-report').innerHTML=values.map(item=>`<div class="report-line"><span>${item.category}</span><div><i style="width:${item.value/max*100}%"></i></div><b>${money(item.value).replace('.00','')}</b></div>`).join('');const healthy=state.items.filter(item=>statusOf(item)==='healthy').length,low=state.items.filter(item=>statusOf(item)==='low').length,out=state.items.filter(item=>statusOf(item)==='out').length,total=Math.max(1,state.items.length),healthyDeg=healthy/total*360,lowDeg=low/total*360;document.getElementById('health-donut').style.background=`conic-gradient(var(--green) 0 ${healthyDeg}deg,var(--amber) ${healthyDeg}deg ${healthyDeg+lowDeg}deg,var(--red) ${healthyDeg+lowDeg}deg 360deg)`;document.getElementById('health-percent').textContent=`${Math.round(healthy/total*100)}%`;document.getElementById('healthy-items').textContent=healthy;document.getElementById('low-items').textContent=low;document.getElementById('out-items').textContent=out;const best=[...state.items].sort((a,b)=>b.qty-a.qty)[0],valuable=[...state.items].sort((a,b)=>b.qty*b.price-a.qty*a.price)[0],average=state.items.length?state.items.reduce((sum,item)=>sum+item.price,0)/state.items.length:0;document.getElementById('best-stocked').textContent=best?`${best.name} · ${best.qty}`:'—';document.getElementById('highest-value').textContent=valuable?valuable.sku:'—';document.getElementById('average-price').textContent=money(average);}
function render(){renderInventory();renderMetrics();renderMovements();renderReports();populateMovementProducts();}
function record(item,type,qty,note){if(type==='receipt')item.qty+=qty;else if(type==='sale')item.qty=Math.max(0,item.qty-qty);else item.qty=qty;state.movements.unshift({id:uid('move'),itemId:item.id,product:item.name,type,qty,note,time:new Date().toISOString()});state.movements=state.movements.slice(0,40);save();render();}
function openItem(item){document.getElementById('item-title').textContent=item?'Edit product':'Add a product';document.getElementById('item-id').value=item?.id||'';document.getElementById('name').value=item?.name||'';document.getElementById('sku').value=item?.sku||'';document.getElementById('item-category').value=item?.category||'Accessories';document.getElementById('price').value=item?.price??12.5;document.getElementById('quantity').value=item?.qty??10;document.getElementById('threshold').value=item?.threshold??5;itemDialog.showModal();}
function populateMovementProducts(){const select=document.getElementById('movement-item'),current=select.value;select.innerHTML=state.items.map(item=>`<option value="${item.id}">${safe(item.name)} · ${item.qty} in stock</option>`).join('');if(state.items.some(item=>item.id===current))select.value=current;updateMovementPreview();}
function openMovement(id){populateMovementProducts();if(id)document.getElementById('movement-item').value=id;document.getElementById('movement-type').value='receipt';document.getElementById('movement-quantity').value=1;document.getElementById('movement-note').value='';updateMovementPreview();movementDialog.showModal();}
function updateMovementPreview(){const item=state.items.find(product=>product.id===document.getElementById('movement-item').value);if(!item){document.getElementById('movement-preview').textContent='Add a product before recording a movement.';return;}const type=document.getElementById('movement-type').value,qty=Math.max(0,Number(document.getElementById('movement-quantity').value)||0),next=type==='receipt'?item.qty+qty:type==='sale'?Math.max(0,item.qty-qty):qty;document.getElementById('movement-preview').textContent=`${item.name}: ${item.qty} units → ${next} units`;}
['search','category','status','sort'].forEach(id=>document.getElementById(id).addEventListener(id==='search'?'input':'change',renderInventory));
tbody.onclick=event=>{const button=event.target.closest('button');if(!button)return;const item=state.items.find(product=>product.id===(button.dataset.id||button.dataset.edit||button.dataset.delete));if(button.dataset.quick){record(item,button.dataset.quick==='plus'?'receipt':'sale',1,'Quick table adjustment');toast(`${item.name} adjusted`);}if(button.dataset.edit)openItem(item);if(button.dataset.delete&&confirm(`Delete ${item.name} and its local stock record?`)){state.items=state.items.filter(product=>product.id!==item.id);save();render();toast('Product deleted');}};
document.getElementById('add').onclick=()=>openItem();document.querySelectorAll('.close-item').forEach(button=>button.onclick=()=>itemDialog.close());document.getElementById('item-form').onsubmit=event=>{event.preventDefault();const id=document.getElementById('item-id').value;const values={name:document.getElementById('name').value.trim(),sku:document.getElementById('sku').value.trim().toUpperCase(),category:document.getElementById('item-category').value,price:Number(document.getElementById('price').value),qty:Number(document.getElementById('quantity').value),threshold:Number(document.getElementById('threshold').value)};if(state.items.some(item=>item.sku===values.sku&&item.id!==id))return toast('That SKU is already in use');const existing=state.items.find(item=>item.id===id);if(existing)Object.assign(existing,values);else state.items.unshift({id:uid('item'),...values});save();render();itemDialog.close();toast(existing?'Product updated':'Product added');};
document.getElementById('movement-button').onclick=()=>openMovement();document.querySelectorAll('.close-movement').forEach(button=>button.onclick=()=>movementDialog.close());['movement-item','movement-type','movement-quantity'].forEach(id=>document.getElementById(id).addEventListener('input',updateMovementPreview));document.getElementById('movement-form').onsubmit=event=>{event.preventDefault();const item=state.items.find(product=>product.id===document.getElementById('movement-item').value);if(!item)return toast('Choose a product');const type=document.getElementById('movement-type').value,qty=Number(document.getElementById('movement-quantity').value);if(type==='sale'&&qty>item.qty)return toast(`Only ${item.qty} units are available`);record(item,type,qty,document.getElementById('movement-note').value.trim());movementDialog.close();showView('movements');toast('Stock movement saved');};
document.getElementById('alert-list').onclick=event=>{const button=event.target.closest('[data-restock]');if(button)openMovement(button.dataset.restock);};
function csvCell(value){return`"${String(value).replaceAll('"','""')}"`;}
function download(content,name,type){const link=document.createElement('a');link.href=URL.createObjectURL(new Blob([content],{type}));link.download=name;link.click();setTimeout(()=>URL.revokeObjectURL(link.href),0);}
document.getElementById('export').onclick=()=>{const rows=['Product,SKU,Category,Price,Quantity,Low stock threshold,Status',...state.items.map(item=>[item.name,item.sku,item.category,item.price,item.qty,item.threshold,statusOf(item)].map(csvCell).join(','))];download(rows.join('\n'),'stockroom-inventory.csv','text/csv');toast('Inventory exported');};
document.getElementById('export-movements').onclick=()=>{const rows=['Product,Type,Quantity,Reference,Time',...state.movements.map(item=>[item.product,item.type,item.qty,item.note,new Date(item.time).toLocaleString()].map(csvCell).join(','))];download(rows.join('\n'),'stockroom-movements.csv','text/csv');toast('Movement log exported');};
document.getElementById('download-report').onclick=()=>{const low=state.items.filter(item=>statusOf(item)!=='healthy'),value=state.items.reduce((sum,item)=>sum+item.price*item.qty,0);download(`STOCKROOM INVENTORY SUMMARY\n\nProducts: ${state.items.length}\nUnits on hand: ${state.items.reduce((sum,item)=>sum+item.qty,0)}\nInventory value: ${money(value)}\nNeed attention: ${low.length}\n\nLOW STOCK\n${low.map(item=>`- ${item.name}: ${item.qty} units (alert at ${item.threshold})`).join('\n')||'None'}`,'stockroom-summary.txt','text/plain');toast('Summary downloaded');};
document.getElementById('reset').onclick=()=>{if(confirm('Reset this local Stockroom workspace to the sample inventory?')){state=cloneDefaults();save();render();toast('Demo workspace reset');}};
function showView(view,updateUrl=true){const valid=['inventory','movements','reports'];const selected=valid.includes(view)?view:'inventory';document.querySelectorAll('.app-view').forEach(section=>section.hidden=section.id!==`${selected}-view`);document.querySelectorAll('aside nav button').forEach(button=>button.classList.toggle('active',button.dataset.view===selected));if(updateUrl)history.replaceState(null,'',`#${selected}`);window.scrollTo({top:0,behavior:'smooth'});}
document.querySelectorAll('aside nav button').forEach(button=>button.onclick=()=>showView(button.dataset.view));
showView(location.hash.slice(1),false);
render();
