const sample=`Full Name,Email Address,Company,Signup Date,Plan
  Alex Morgan  ,alex@example.com,North & Co,2026-02-04,Pro
Sam Lee,sam.example.com,Fieldwork,2026-02-11,Starter
Alex Morgan,alex@example.com,North & Co,2026-02-04,Pro
Priya Shah,priya@studio.co.uk,,2026-03-01,Pro
,,,,
Jon Bell,jon@bell.io,Acme,2026-03-06,Starter`;
const input=document.getElementById('csv-input');
let cleaned=[];let currentDelimiter=',';let previousSource='';let currentName='Untitled dataset';

function toast(message){const el=document.getElementById('toast');el.textContent=message;el.classList.add('show');clearTimeout(toast.timer);toast.timer=setTimeout(()=>el.classList.remove('show'),2200);}
function safe(value){const node=document.createElement('span');node.textContent=String(value??'');return node.innerHTML;}
function detectDelimiter(text){const first=(text.split(/\r?\n/)[0]||'');const choices=[',',';','\t'];return choices.sort((a,b)=>first.split(b).length-first.split(a).length)[0];}
function parseCSV(text,delimiter){const rows=[];let row=[];let value='';let quoted=false;for(let i=0;i<text.length;i++){const char=text[i];if(char==='"'){if(quoted&&text[i+1]==='"'){value+='"';i++;}else quoted=!quoted;}else if(char===delimiter&&!quoted){row.push(value);value='';}else if((char==='\n'||char==='\r')&&!quoted){if(char==='\r'&&text[i+1]==='\n')i++;row.push(value);rows.push(row);row=[];value='';}else value+=char;}if(value.length||row.length){row.push(value);rows.push(row);}return rows;}
function toCSV(rows,delimiter=','){return rows.map(row=>row.map(value=>{const text=String(value??'');return /["\n\r,;]/.test(text)?`"${text.replaceAll('"','""')}"`:text;}).join(delimiter)).join('\n');}
function isEmail(value){return /^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(value);}
function normaliseHeader(value,index){return value.trim().toLowerCase().replace(/[^a-z0-9]+/g,'_').replace(/^_+|_+$/g,'')||`column_${index+1}`;}
function analyse(rows){if(!rows.length)return{rows:0,columns:0,empty:0,duplicates:0,emptyRows:0,invalidEmails:0};const width=Math.max(...rows.map(row=>row.length));let empty=0,emptyRows=0,invalidEmails=0;const seen=new Set();let duplicates=0;const emailColumns=(rows[0]||[]).map((value,index)=>/email/i.test(value)?index:-1).filter(index=>index>=0);rows.slice(1).forEach(row=>{const values=Array.from({length:width},(_,index)=>(row[index]||'').trim());empty+=values.filter(value=>!value).length;if(!values.some(Boolean))emptyRows++;const key=values.join('\u0000').toLowerCase();if(seen.has(key)&&values.some(Boolean))duplicates++;else seen.add(key);emailColumns.forEach(index=>{if(values[index]&&!isEmail(values[index]))invalidEmails++;});});return{rows:Math.max(0,rows.length-1),columns:width,empty,duplicates,emptyRows,invalidEmails};}
function selectedDelimiter(){const value=document.getElementById('delimiter').value;return value==='auto'?detectDelimiter(input.value):value==='\\t'?'\t':value;}

function updateSourceMetrics(){const rows=parseCSV(input.value,selectedDelimiter());const info=analyse(rows);document.getElementById('row-count').textContent=info.rows;document.getElementById('column-count').textContent=info.columns;document.getElementById('issue-count').textContent=info.empty+info.duplicates+info.emptyRows+info.invalidEmails;document.getElementById('row-note').textContent=info.rows?'Source rows detected':'Waiting for data';document.getElementById('type-note').textContent=info.columns?`${info.columns} fields detected`:'Not profiled';document.getElementById('issue-note').textContent=info.rows?'Before cleaning':'No analysis yet';}
function inferType(values){const nonEmpty=values.filter(Boolean);if(!nonEmpty.length)return'empty';if(nonEmpty.every(value=>!Number.isNaN(Number(value))))return'number';if(nonEmpty.every(value=>/^\d{4}-\d{2}-\d{2}$/.test(value)))return'date';if(nonEmpty.every(isEmail))return'email';return'text';}
function buildProfile(rows){if(rows.length<2)return;const headers=rows[0];const body=rows.slice(1);document.getElementById('column-profile').innerHTML=headers.map((header,index)=>{const values=body.map(row=>(row[index]||'').trim());const complete=values.length?Math.round(values.filter(Boolean).length/values.length*100):100;const unique=new Set(values.filter(Boolean).map(value=>value.toLowerCase())).size;return`<article class="column-card"><header><h3>${safe(header)}</h3><span class="type-badge">${inferType(values)}</span></header><p>${complete}% complete</p><div class="profile-bar"><i style="width:${complete}%"></i></div><footer><span>${unique} unique</span><span>${values.length-unique} repeated</span></footer></article>`;}).join('');}
function renderTable(rows){const table=document.getElementById('preview');if(!rows.length){table.innerHTML='<tbody><tr><td class="empty">Your cleaned dataset will appear here.</td></tr></tbody>';return;}const emailColumns=rows[0].map((header,index)=>/email/i.test(header)?index:-1).filter(index=>index>=0);table.innerHTML=`<thead><tr>${rows[0].map(header=>`<th>${safe(header)}</th>`).join('')}</tr></thead><tbody>${rows.slice(1,11).map(row=>`<tr>${rows[0].map((_,index)=>{const value=row[index]||'';const invalid=emailColumns.includes(index)&&value&&!isEmail(value);return`<td class="${invalid?'invalid':''}">${safe(value)||'—'}</td>`;}).join('')}</tr>`).join('')}</tbody>`;document.getElementById('preview-count').textContent=Math.min(10,Math.max(0,rows.length-1));document.getElementById('preview-foot').hidden=false;}
function report(before,after,rules){const issues=[];if(before.duplicates)issues.push({fixed:rules.duplicates,title:`${before.duplicates} duplicate row${before.duplicates===1?'':'s'}`,copy:rules.duplicates?'Removed while keeping the first record.':'Still present because duplicate removal is off.'});if(before.emptyRows)issues.push({fixed:rules.emptyRows,title:`${before.emptyRows} empty row${before.emptyRows===1?'':'s'}`,copy:rules.emptyRows?'Removed from the output.':'Still present because empty-row removal is off.'});if(before.empty)issues.push({fixed:before.empty>after.empty,title:`${before.empty} empty cell${before.empty===1?'':'s'}`,copy:before.empty>after.empty?'Empty-only rows or columns were removed.':'Kept so you can review the missing values.'});if(after.invalidEmails)issues.push({fixed:false,title:`${after.invalidEmails} invalid email ${after.invalidEmails===1?'value':'values'}`,copy:'Highlighted in the preview for manual review.'});if(!issues.length)issues.push({fixed:true,title:'No quality problems detected',copy:'This dataset already follows the selected quality rules.'});document.getElementById('issue-list').innerHTML=issues.map(issue=>`<div class="issue ${issue.fixed?'fixed':''}"><i>${issue.fixed?'✓':'!'}</i><div><b>${safe(issue.title)}</b><p>${safe(issue.copy)}</p></div></div>`).join('');}

function cleanData(){const raw=input.value.trim();if(!raw)return toast('Add or import CSV data first');previousSource=input.value;document.getElementById('undo').disabled=false;currentDelimiter=selectedDelimiter();let rows=parseCSV(input.value,currentDelimiter);if(rows.length<2)return toast('The CSV needs a header and at least one data row');const before=analyse(rows);const rules={trim:document.getElementById('trim').checked,duplicates:document.getElementById('duplicates').checked,emptyRows:document.getElementById('empty-rows').checked,headers:document.getElementById('headers').checked,emailCheck:document.getElementById('email-check').checked,emptyColumns:document.getElementById('empty-columns').checked};if(rules.trim)rows=rows.map(row=>row.map(value=>value.trim()));if(rules.emptyRows)rows=rows.filter((row,index)=>index===0||row.some(value=>value.trim()));if(rules.emptyColumns){const width=Math.max(...rows.map(row=>row.length));const keep=Array.from({length:width},(_,index)=>index).filter(index=>index===0||rows.slice(1).some(row=>(row[index]||'').trim()));rows=rows.map(row=>keep.map(index=>row[index]||''));}if(rules.headers)rows[0]=rows[0].map(normaliseHeader);if(rules.duplicates){const seen=new Set();rows=rows.filter((row,index)=>{if(index===0)return true;const key=row.join('\u0000').toLowerCase();if(seen.has(key))return false;seen.add(key);return true;});}const width=rows[0].length;cleaned=rows.map(row=>Array.from({length:width},(_,index)=>row[index]||''));const after=analyse(cleaned);const issues=after.empty+after.duplicates+after.emptyRows+(rules.emailCheck?after.invalidEmails:0);const score=Math.max(55,100-Math.min(45,issues*6));document.getElementById('score').textContent=score;document.getElementById('score-note').textContent=score>=95?'Excellent data health':score>=80?'Good, with minor review':'Review flagged issues';document.getElementById('score-ring').style.background=`conic-gradient(var(--green) ${score*3.6}deg,#e9eeeb 0)`;document.getElementById('row-count').textContent=after.rows;document.getElementById('column-count').textContent=after.columns;document.getElementById('issue-count').textContent=issues;document.getElementById('issue-note').textContent='After selected rules';document.getElementById('result-label').textContent=`${after.rows} clean rows · ${after.columns} columns · ${before.duplicates+before.emptyRows+Math.max(0,before.empty-after.empty)} fixes applied`;renderTable(cleaned);buildProfile(cleaned);report(before,after,rules);['copy','download','export-csv','export-json','copy-all'].forEach(id=>document.getElementById(id).disabled=false);input.value=toCSV(cleaned,currentDelimiter);const history=JSON.parse(localStorage.getItem('tidydata-history-v3')||'[]');history.unshift({name:currentName,rows:after.rows,columns:after.columns,score,time:new Date().toISOString()});localStorage.setItem('tidydata-history-v3',JSON.stringify(history.slice(0,5)));toast('Dataset profiled and cleaned');}

function loadText(text,name){input.value=text;currentName=name||'Untitled dataset';document.getElementById('file-name').textContent=currentName;cleaned=[];updateSourceMetrics();toast(`${currentName} loaded`);}
function readFile(file){if(!file)return;if(file.size>5*1024*1024)return toast('Please choose a CSV smaller than 5 MB');const reader=new FileReader();reader.onload=()=>loadText(reader.result,file.name);reader.readAsText(file);}
document.getElementById('sample').onclick=()=>loadText(sample,'customer-signups-sample.csv');document.getElementById('file').onchange=event=>readFile(event.target.files[0]);input.oninput=updateSourceMetrics;document.getElementById('delimiter').onchange=updateSourceMetrics;document.getElementById('clean').onclick=cleanData;
document.getElementById('clear').onclick=()=>{previousSource=input.value;input.value='';cleaned=[];currentName='Untitled dataset';document.getElementById('file-name').textContent=currentName;document.getElementById('undo').disabled=!previousSource;document.getElementById('preview').innerHTML='<tbody><tr><td class="empty">Your cleaned dataset will appear here.</td></tr></tbody>';document.getElementById('preview-foot').hidden=true;document.getElementById('column-profile').innerHTML='<div class="empty">Clean a dataset to build its profile.</div>';document.getElementById('issue-list').innerHTML='<div class="empty">No report available yet.</div>';['copy','download','export-csv','export-json','copy-all'].forEach(id=>document.getElementById(id).disabled=true);document.getElementById('score').textContent='—';updateSourceMetrics();};
document.getElementById('undo').onclick=()=>{if(!previousSource)return;const current=input.value;input.value=previousSource;previousSource=current;updateSourceMetrics();toast('Previous source restored');};
document.getElementById('select-rules').onclick=()=>{const boxes=[...document.querySelectorAll('.rules input')];const all=boxes.every(box=>box.checked);boxes.forEach(box=>box.checked=!all);document.getElementById('select-rules').textContent=all?'Select all':'Clear all';};
const dropZone=document.getElementById('drop-zone');['dragenter','dragover'].forEach(type=>dropZone.addEventListener(type,event=>{event.preventDefault();dropZone.classList.add('drag');}));['dragleave','drop'].forEach(type=>dropZone.addEventListener(type,event=>{event.preventDefault();dropZone.classList.remove('drag');}));dropZone.addEventListener('drop',event=>readFile(event.dataTransfer.files[0]));
function download(content,name,type){const link=document.createElement('a');link.href=URL.createObjectURL(new Blob([content],{type}));link.download=name;link.click();setTimeout(()=>URL.revokeObjectURL(link.href),0);}
function exportCSV(){if(!cleaned.length)return;download(toCSV(cleaned,','),`${currentName.replace(/\.csv$/i,'')}-clean.csv`,'text/csv');toast('Clean CSV downloaded');}
function exportJSON(){if(!cleaned.length)return;const [headers,...rows]=cleaned;const objects=rows.map(row=>Object.fromEntries(headers.map((header,index)=>[header,row[index]||''])));download(JSON.stringify(objects,null,2),`${currentName.replace(/\.csv$/i,'')}-clean.json`,'application/json');toast('JSON file downloaded');}
async function copyAll(){if(!cleaned.length)return;await navigator.clipboard.writeText(toCSV(cleaned,','));toast('Clean data copied');}
document.getElementById('download').onclick=exportCSV;document.getElementById('export-csv').onclick=exportCSV;document.getElementById('export-json').onclick=exportJSON;document.getElementById('copy').onclick=copyAll;document.getElementById('copy-all').onclick=copyAll;
function showView(view,updateUrl=true){const valid=['workspace','profile','exports'];const selected=valid.includes(view)?view:'workspace';document.querySelectorAll('.app-view').forEach(section=>section.hidden=section.id!==`${selected}-view`);document.querySelectorAll('aside nav button').forEach(button=>button.classList.toggle('active',button.dataset.view===selected));if(updateUrl)history.replaceState(null,'',`#${selected}`);window.scrollTo({top:0,behavior:'smooth'});}
document.querySelectorAll('aside nav button').forEach(button=>button.onclick=()=>showView(button.dataset.view));
showView(location.hash.slice(1),false);
updateSourceMetrics();
