const input=document.getElementById('csv-input');let cleaned=[];
function parseCSV(text){const rows=[];let row=[],cell='',quoted=false;for(let i=0;i<text.length;i++){const c=text[i],next=text[i+1];if(c==='"'&&quoted&&next==='"'){cell+='"';i++}else if(c==='"'){quoted=!quoted}else if(c===','&&!quoted){row.push(cell);cell=''}else if((c==='\n'||c==='\r')&&!quoted){if(c==='\r'&&next==='\n')i++;row.push(cell);rows.push(row);row=[];cell=''}else cell+=c}if(cell||row.length){row.push(cell);rows.push(row)}return rows}
function toCSV(rows){return rows.map(r=>r.map(c=>/[",\n]/.test(c)?`"${c.replaceAll('"','""')}"`:c).join(',')).join('\n')}
function analyse(rows){const body=rows.slice(1),empty=body.flat().filter(x=>!x.trim()).length,seen=new Set(),dupes=body.filter(r=>{const k=r.join('\u0000').toLowerCase();if(seen.has(k))return true;seen.add(k);return false}).length;document.getElementById('row-count').textContent=body.length;document.getElementById('column-count').textContent=rows[0]?.length||0;document.getElementById('empty-count').textContent=empty;document.getElementById('duplicate-count').textContent=dupes;return{empty,dupes}}
function render(rows){const table=document.getElementById('preview');if(!rows.length){table.innerHTML='<tbody><tr><td class="empty">Your cleaned data will appear here.</td></tr></tbody>';return}table.innerHTML=`<thead><tr>${rows[0].map(h=>`<th>${escapeHTML(h||'Untitled')}</th>`).join('')}</tr></thead><tbody>${rows.slice(1,101).map(r=>`<tr>${rows[0].map((_,i)=>`<td>${escapeHTML(r[i]||'—')}</td>`).join('')}</tr>`).join('')}</tbody>`}
function escapeHTML(x){const n=document.createElement('span');n.textContent=x;return n.innerHTML}
function refresh(){analyse(parseCSV(input.value))}input.addEventListener('input',refresh);
document.getElementById('sample').onclick=()=>{input.value='name, email, company, status\n  Maya Chen  ,maya@example.com,North & Co,active\nSam Reed,sam@example.com, Bright Labs ,active\nSam Reed,sam@example.com, Bright Labs ,active\nPriya Shah,,Orchard Studio,pending\n,,,';refresh();toast('Sample data loaded')};
document.getElementById('file').onchange=event=>{const file=event.target.files[0];if(!file)return;const reader=new FileReader();reader.onload=()=>{input.value=reader.result;refresh();toast(`${file.name} imported`)};reader.readAsText(file)};
document.getElementById('clear').onclick=()=>{input.value='';cleaned=[];refresh();render([]);document.getElementById('download').disabled=true;document.getElementById('report').hidden=true};
document.getElementById('clean').onclick=()=>{let rows=parseCSV(input.value);if(!rows.length)return toast('Add CSV data first');const before=analyse(rows);if(document.getElementById('trim').checked)rows=rows.map(r=>r.map(x=>x.trim()));if(document.getElementById('empty-rows').checked)rows=rows.filter((r,i)=>i===0||r.some(x=>x.trim()));if(document.getElementById('duplicates').checked){const seen=new Set();rows=rows.filter((r,i)=>{if(i===0)return true;const k=r.join('\u0000').toLowerCase();if(seen.has(k))return false;seen.add(k);return true})}const width=rows[0].length;cleaned=rows.map(r=>Array.from({length:width},(_,i)=>r[i]||''));render(cleaned);const after=analyse(cleaned),fixes=before.empty-after.empty+before.dupes-after.dupes;document.getElementById('result-label').textContent=`Showing ${Math.max(0,cleaned.length-1)} clean rows.`;document.getElementById('download').disabled=false;document.getElementById('report').hidden=false;document.getElementById('score').textContent=Math.max(75,100-after.empty*2-after.dupes*5);document.getElementById('report-copy').textContent=`${fixes} issue${fixes===1?'':'s'} fixed. ${cleaned.length-1} rows are ready to export.`;toast('Data cleaned successfully')};
document.getElementById('download').onclick=()=>{const blob=new Blob([toCSV(cleaned)],{type:'text/csv'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='tidydata-clean.csv';a.click();URL.revokeObjectURL(a.href);toast('Clean CSV downloaded')};
function toast(msg){const el=document.getElementById('toast');el.textContent=msg;el.classList.add('show');setTimeout(()=>el.classList.remove('show'),2200)}refresh();
