const messages=document.getElementById('messages');const replies=document.getElementById('quick-replies');const form=document.getElementById('chat-form');const input=document.getElementById('chat-input');
const emptyState=()=>({idea:'',type:'',industry:'',goal:'',audience:'',features:[],timeline:'',budget:'',style:'',integrations:[],notes:[]});
let state=emptyState();let currentField='idea';let asked=new Set();let refining=false;let generated=false;
const fieldMeta={type:['▣','Project'],industry:['⌂','Industry'],goal:['↗','Goal'],audience:['◎','Audience'],features:['✦','Features'],timeline:['◷','Timeline'],budget:['£','Budget'],style:['◐','Style'],integrations:['⌘','Integrations']};
const featureDictionary={booking:['booking','reservation','appointment','calendar'],payments:['payment','stripe','checkout','pay'],shop:['shop','store','cart','ecommerce','e-commerce','products'],accounts:['login','account','member','membership','sign in'],dashboard:['dashboard','admin','portal','reporting'],forms:['form','lead form','contact form','enquiry'],chat:['chat','chatbot','assistant','bot'],automation:['automation','automate','workflow'],email:['email','newsletter','mailing'],database:['database','records','data'],analytics:['analytics','tracking','metrics'],search:['search','filter'],inventory:['inventory','stock'],content:['blog','cms','content'],seo:['seo','google'],mobile:['mobile','responsive','phone'],api:['api','integration','integrate']};
featureDictionary.booking.push('book');
featureDictionary.menu=['menu','food list'];
featureDictionary.directions=['direction','find us','location','map'];
const typeFeatures={
  'Restaurant website':['Online table booking','Seasonal menu management','Opening hours & directions','Allergy information','Email confirmations','Local SEO'],
  'E-commerce website':['Product catalogue','Secure checkout','Stock management','Customer accounts','Order emails','Sales analytics'],
  'Business website':['Conversion-focused pages','Enquiry forms','CMS content editing','Testimonials','Analytics','Technical SEO'],
  'Web application':['Secure accounts','Role-based dashboard','Search & filters','Data export','Notifications','Admin tools'],
  'Automation':['Trigger and action builder','Integration monitoring','Error handling','Activity log','Scheduled runs','Email alerts'],
  'Landing page':['Clear value proposition','Lead capture form','Social proof','Analytics','Fast mobile layout','SEO metadata']
};

function safe(value){const node=document.createElement('span');node.textContent=String(value??'');return node.innerHTML;}
function toast(message){const el=document.getElementById('toast');el.textContent=message;el.classList.add('show');clearTimeout(toast.timer);toast.timer=setTimeout(()=>el.classList.remove('show'),2100);}
function add(text,role='bot'){const el=document.createElement('div');el.className=`message ${role}`;el.textContent=text;messages.append(el);messages.scrollTop=messages.scrollHeight;}
function botSay(text,role='bot'){return new Promise(resolve=>{const typing=document.createElement('div');typing.className='message bot typing';typing.innerHTML='<i></i><i></i><i></i>';messages.append(typing);messages.scrollTop=messages.scrollHeight;setTimeout(()=>{typing.remove();add(text,role);resolve();},360);});}
function setReplies(options=[],finish=false){replies.innerHTML=options.map(option=>`<button type="button" class="${finish&&option.includes('brief')?'finish':''}">${safe(option)}</button>`).join('');replies.querySelectorAll('button').forEach(button=>button.onclick=()=>processMessage(button.textContent));}
function uniquePush(list,value){if(value&&!list.some(item=>item.toLowerCase()===value.toLowerCase()))list.push(value);}
function detect(text){const lower=text.toLowerCase();const found={};
  if(/restaurant|cafe|café|diner|food business/.test(lower)){found.industry='Restaurant & hospitality';found.type='Restaurant website';}
  else if(/shop|store|e-?commerce|sell online|checkout|products online/.test(lower)){found.type='E-commerce website';found.industry=state.industry||'Retail & e-commerce';}
  else if(/automat|workflow|repetitive|script|connect .* (to|with)/.test(lower))found.type='Automation';
  else if(/landing page|one page/.test(lower))found.type='Landing page';
  else if(/web app|application|portal|platform|dashboard|saas|software/.test(lower))found.type='Web application';
  else if(/website|web site|site/.test(lower))found.type='Business website';
  const industries=[['Healthcare & wellness',/clinic|doctor|health|wellness|therapy|dentist/],['Property & real estate',/property|estate agent|real estate|letting/],['Professional services',/agency|consult|account|legal|law firm/],['Education',/school|course|student|education|tutor/],['Fitness',/gym|fitness|trainer|workout/],['Non-profit',/charity|nonprofit|non-profit/]];for(const[industry,pattern]of industries)if(pattern.test(lower))found.industry=industry;
  if(/lead|enquir|more clients|new customers|conversion/.test(lower))found.goal='Generate qualified leads';else if(/save time|manual|repetitive|efficien|faster/.test(lower))found.goal='Save time and reduce manual work';else if(/sell|revenue|orders|online sales/.test(lower))found.goal='Increase online sales';else if(/book|reservation|appointment/.test(lower))found.goal='Increase online bookings';else if(/present|showcase|portfolio|credib|professional online/.test(lower))found.goal='Present the business professionally';else if(/customer experience|easier for customers|self.service/.test(lower))found.goal='Improve the customer experience';
  const hasTeam=/team|staff|employee|internal/.test(lower),hasCustomers=/customer|client|guest|patient|student|visitor|public/.test(lower);if(hasTeam&&hasCustomers)found.audience='Customers and internal team';else if(hasTeam)found.audience='Internal team';else if(hasCustomers)found.audience='Customers / public users';
  const timelineMatch=text.match(/(?:within|in|about|around|by)\s+(\d+\s*(?:day|week|month)s?)/i);if(timelineMatch)found.timeline=timelineMatch[1];else if(/asap|urgent|as soon as possible/.test(lower))found.timeline='As soon as possible';else if(/flexible|no rush|not sure when/.test(lower))found.timeline='Flexible';
  const budgetMatch=text.match(/(?:£|\$|€)\s?\d[\d,]*(?:\s*(?:-|to|–)\s*(?:£|\$|€)?\s?\d[\d,]*)?|\d[\d,]*\s*(?:pounds|dollars|euros)/i);if(budgetMatch)found.budget=budgetMatch[0].replace(/\s+/g,' ').trim();else if(/budget.*flexible|not sure.*budget|budget.*not sure/.test(lower))found.budget='Not decided yet';
  const styles=['modern','minimal','luxury','premium','playful','professional','bold','friendly','clean','dark','colourful','colorful'];const styleHits=styles.filter(word=>lower.includes(word));if(styleHits.length)found.style=styleHits.map(word=>word[0].toUpperCase()+word.slice(1)).join(' + ');
  found.features=[];Object.entries(featureDictionary).forEach(([label,words])=>{if(words.some(word=>lower.includes(word)))uniquePush(found.features,label[0].toUpperCase()+label.slice(1));});
  const integrationNames=['Google Sheets','Excel','Stripe','Shopify','WordPress','Slack','Gmail','Outlook','HubSpot','Airtable','Zapier'];found.integrations=integrationNames.filter(name=>lower.includes(name.toLowerCase()));
  return found;
}
function applyDetected(found,text,field){const changes=[];for(const key of ['type','industry','goal','audience','timeline','budget','style']){if(found[key]&&state[key]!==found[key]){state[key]=found[key];changes.push(`${key}: ${found[key]}`);}}(found.features||[]).forEach(feature=>{const before=state.features.length;uniquePush(state.features,feature);if(state.features.length>before)changes.push(`feature: ${feature}`);});(found.integrations||[]).forEach(item=>{const before=state.integrations.length;uniquePush(state.integrations,item);if(state.integrations.length>before)changes.push(`integration: ${item}`);});
  const value=text.trim();if(field==='idea'&&!state.idea){state.idea=value;changes.push('project idea');}if(field==='type'&&!state.type){state.type=value;changes.push(`project: ${value}`);}if(field==='goal'&&!state.goal){state.goal=value;changes.push(`goal: ${value}`);}if(field==='audience'&&!state.audience){state.audience=value;changes.push(`audience: ${value}`);}if(field==='timeline'&&!state.timeline){state.timeline=value;changes.push(`timeline: ${value}`);}if(field==='budget'&&!state.budget){state.budget=value;changes.push(`budget: ${value}`);}if(field==='style'&&!state.style){state.style=value;changes.push(`style: ${value}`);}if(field==='features'&&!found.features.length){value.split(/,|\+| and /i).map(item=>item.trim()).filter(Boolean).slice(0,6).forEach(feature=>uniquePush(state.features,feature));changes.push('requested features');}if(field==='integrations'&&!found.integrations.length&&value.toLowerCase()!=='not sure yet'){value.split(/,|\+| and /i).map(item=>item.trim()).filter(Boolean).slice(0,6).forEach(item=>uniquePush(state.integrations,item));changes.push('integrations');}if(value.toLowerCase()==='not sure yet'||/i don.t know|not sure/.test(value.toLowerCase()))applyFallback(field,changes);return changes;}
function applyFallback(field,changes){const fallbacks={goal:'Create a clear, easy-to-use customer experience',audience:'Customers / public users',timeline:'Flexible',budget:'Not decided yet',style:'Modern + professional'};if(fallbacks[field]){state[field]=fallbacks[field];changes.push(`${field}: ${fallbacks[field]}`);}if(field==='features'){recommendedForType().slice(0,3).forEach(feature=>uniquePush(state.features,feature));changes.push('recommended starter features');}if(field==='integrations')changes.push('integrations can be confirmed later');}
function recommendedForType(){return typeFeatures[state.type]||typeFeatures['Business website'];}
function contextSummary(changes){const useful=changes.filter(change=>!['project idea','requested features'].includes(change));if(!useful.length)return'I’ve added that to the project notes.';const items=useful.slice(0,4).map(change=>change.replace(/^\w+: /,'')).join(', ');return`Got it — I picked up ${items}${useful.length>4?' and a few more details':''}. I’ll use that context from here.`;}
function answerQuestion(text){const lower=text.toLowerCase();if(/are you (ai|real)|how do you understand|brain/.test(lower))return'I’m a smart local planning assistant rather than a remote AI model. I recognise useful details in natural language, remember them during this conversation, and choose the next question from what is still missing.';if(/how much|cost|price|budget/.test(lower))return`Cost depends mainly on scope. For a ${state.type||'digital project'}, integrations, accounts, payments, and admin tools usually have the biggest impact. I’ll include a realistic scope note once I know the must-have features.`;if(/how long|timeline|time.*take/.test(lower))return`A focused site can often be delivered in a few weeks; a data-heavy app or automation usually needs more discovery and testing. I’ll shape the roadmap around your target date.`;if(/what feature|what should|recommend/.test(lower))return`For ${state.type||'this project'}, I’d start with ${recommendedForType().slice(0,3).join(', ')}. We can keep the first release focused and add the rest later.`;return'';}
function completion(){const fields=[state.type,state.goal,state.audience,state.features.length,state.timeline,state.budget];return Math.round(fields.filter(Boolean).length/fields.length*100);}
function updateContext(){const entries=[];Object.entries(fieldMeta).forEach(([key,[icon,label]])=>{const value=Array.isArray(state[key])?state[key].join(', '):state[key];if(value)entries.push({icon,label,value});});document.getElementById('context-list').innerHTML=entries.length?entries.map(item=>`<div class="context-item"><i>${item.icon}</i><div><span>${item.label}</span><b title="${safe(item.value)}">${safe(item.value)}</b></div></div>`).join(''):'<div class="context-empty">Tell BriefBot about your idea. Useful details will appear here as it listens.</div>';document.getElementById('memory-count').textContent=`${entries.length} detail${entries.length===1?'':'s'}`;const percent=completion();document.getElementById('progress-percent').textContent=`${percent}%`;document.getElementById('progress-bar').style.width=`${percent}%`;document.getElementById('confidence-bar').style.width=`${Math.min(96,entries.length*13)}%`;document.getElementById('confidence-copy').textContent=entries.length<2?'Listening…':entries.length<5?'Building context':entries.length<7?'Strong context':'Ready to plan';}
function chooseNext(){if(!state.idea&&!state.type)return'idea';if(!state.type)return'type';if(state.type==='Automation'&&!state.integrations.length&&!asked.has('integrations'))return'integrations';if(!state.goal)return'goal';if(!state.audience)return'audience';if(!state.features.length)return'features';if(['Restaurant website','E-commerce website','Business website','Landing page'].includes(state.type)&&!state.style&&!asked.has('style'))return'style';if(!state.timeline)return'timeline';if(!state.budget)return'budget';return'complete';}
function questionFor(field){const industry=state.industry||'your business',type=state.type||'project';const map={idea:{text:'Hi — I’m BriefBot. Tell me what you would like to build in your own words. Include the business, users, features, timing, or budget if you already know them.',options:['A business website','A web application','An automation','An online shop']},type:{text:'I understand the idea. Which format fits it best?',options:['Business website','Web application','Automation','E-commerce website','Landing page']},integrations:{text:'Because this is an automation, which tools or information should it connect?',options:['Email + Google Sheets','CRM + email','Files + spreadsheet','Not sure yet']},goal:{text:`For this ${type.toLowerCase()}, what matters most: more enquiries, saved time, bookings, sales, or a stronger presentation?`,options:state.type==='Restaurant website'?['Increase online bookings','Show the menu clearly','Improve customer experience']:state.type==='Automation'?['Save time and reduce manual work','Reduce mistakes','Speed up customer response']:['Generate qualified leads','Increase online sales','Present the business professionally','Improve the customer experience']},audience:{text:`Who will use this most? Think about the main people ${industry.toLowerCase()} needs to serve.`,options:state.type==='Automation'?['Internal team','Customers and internal team','Business owner only']:['Customers / public users','Internal team','Customers and internal team']},features:{text:`What must the first version include? For a ${type.toLowerCase()}, a sensible starting point could be ${recommendedForType().slice(0,3).join(', ')}.`,options:recommendedForType().slice(0,4)},style:{text:'What should the experience feel like? You can choose a direction or describe your own visual style.',options:['Modern + professional','Premium + minimal','Friendly + colourful','Bold + dark']},timeline:{text:`What timing are you working toward for this ${type.toLowerCase()}?`,options:['Within 2 weeks','Around 4 weeks','1–2 months','Flexible']},budget:{text:'What budget range should the plan respect? “Not decided yet” is completely fine.',options:['Under £500','£500–£1,500','£1,500–£3,000','Over £3,000','Not decided yet']}};return map[field];}
async function askNext(){updateContext();currentField=chooseNext();if(currentField==='complete'){generateBrief();return;}asked.add(currentField);const question=questionFor(currentField);await botSay(question.text);setReplies(question.options||[]);input.placeholder=currentField==='features'?'List must-have features…':currentField==='budget'?'Type a range or choose below…':'Type your answer…';input.focus({preventScroll:true});}
async function processMessage(value){value=value.trim();if(!value)return;add(value,'user');input.value='';replies.innerHTML='';const questionReply=answerQuestion(value);const found=detect(value);const changes=applyDetected(found,value,currentField);updateContext();if(refining){await botSay(contextSummary(changes));refining=false;generateBrief(true);return;}if(questionReply&&changes.length===0){await botSay(questionReply);const question=questionFor(currentField);if(question){await botSay(`When you’re ready: ${question.text}`);setReplies(question.options||[]);}return;}await botSay(contextSummary(changes),'insight');await askNext();}

function buildRecommendations(){const recommendations=[...state.features];recommendedForType().forEach(feature=>uniquePush(recommendations,feature));return recommendations.slice(0,6);}
function scopeLevel(){const count=state.features.length+state.integrations.length+(state.type==='Web application'?3:0)+(state.type==='E-commerce website'?2:0);return count>=7?'Advanced build':count>=4?'Standard build':'Focused first release';}
function briefText(){return`${state.type||'DIGITAL PROJECT'} — PROJECT BRIEF\n\nProject idea: ${state.idea||state.type}\nIndustry: ${state.industry||'To confirm'}\nPrimary goal: ${state.goal}\nTarget audience: ${state.audience}\nVisual direction: ${state.style||'To confirm during design'}\nTimeline: ${state.timeline}\nBudget: ${state.budget}\nIntegrations: ${state.integrations.join(', ')||'To confirm'}\n\nMUST-HAVE FEATURES\n${buildRecommendations().map(feature=>`- ${feature}`).join('\n')}\n\nDELIVERY APPROACH\n1. Discovery and content\n2. UX and visual design\n3. Build and integration\n4. Testing and launch\n\nScope level: ${scopeLevel()}\n\nThis brief was generated by BriefBot, a local adaptive portfolio demonstration.`;}
function generateBrief(refined=false){generated=true;currentField='complete';replies.innerHTML='';updateContext();const recommendations=buildRecommendations(),title=`${state.industry?state.industry.split(' & ')[0]+' ':''}${state.type||'digital project'} plan`;document.getElementById('brief-title').textContent=title;document.getElementById('brief-summary').textContent=`A ${scopeLevel().toLowerCase()} focused on ${state.goal.toLowerCase()} for ${state.audience.toLowerCase()}, with a target of ${state.timeline.toLowerCase()}.`;
  const overview=[['Project',state.type],['Industry',state.industry||'To confirm'],['Goal',state.goal],['Timeline',state.timeline],['Budget',state.budget]];document.getElementById('brief-overview').innerHTML=overview.map(([label,value])=>`<article><span>${label}</span><b>${safe(value)}</b></article>`).join('');
  document.getElementById('recommended-features').innerHTML=recommendations.map((feature,index)=>`<div class="feature"><i>✓</i><div><b>${safe(feature)}</b><p>${index<state.features.length?'Requested in the conversation':'Recommended for this project type'}</p></div></div>`).join('');
  const roadmap=[['Discover','Confirm content, users, success measures, and technical constraints.'],['Design',`Create a ${state.style||'clear, professional'} responsive experience and approve key screens.`],['Build','Develop the features, integrations, validation, and management tools.'],['Launch','Test browsers and devices, prepare content, deploy, and monitor the release.']];document.getElementById('roadmap').innerHTML=roadmap.map((step,index)=>`<div class="roadmap-step"><i>${index+1}</i><div><b>${step[0]}</b><p>${safe(step[1])}</p></div></div>`).join('');
  document.getElementById('scope-guidance').innerHTML=`<p><span>Suggested scope</span><b>${scopeLevel()}</b></p><p><span>Primary users</span><b>${safe(state.audience)}</b></p><p><span>Integrations</span><b>${safe(state.integrations.join(', ')||'Confirm in discovery')}</b></p><p><span>Visual direction</span><b>${safe(state.style||'Confirm in discovery')}</b></p><p class="scope-note">Keep the first release centred on the main goal. Extra automation, complex accounts, or advanced reporting can be planned as a second phase.</p>`;
  const brief=document.getElementById('brief');brief.hidden=false;botSay(refined?'I’ve updated the plan using your latest instruction. The refreshed brief is ready below.':'That gives me enough context. I’ve created a practical project plan below—and I used what you said instead of forcing you through a fixed questionnaire.');setTimeout(()=>brief.scrollIntoView({behavior:'smooth',block:'start'}),450);}

form.onsubmit=event=>{event.preventDefault();processMessage(input.value);};
function restart(){state=emptyState();currentField='idea';asked=new Set();refining=false;generated=false;messages.innerHTML='';replies.innerHTML='';document.getElementById('brief').hidden=true;updateContext();start();}
async function start(){await botSay('Hello! I’m BriefBot. I listen for several details at once, remember them, and only ask about what is still missing.');await askNext();}
document.getElementById('restart').onclick=restart;document.getElementById('refine').onclick=async()=>{refining=true;currentField='refine';document.querySelector('.chat-card').scrollIntoView({behavior:'smooth',block:'center'});await botSay('Tell me what you want to change. For example: “Make the budget £2,000, add Stripe payments, and change the style to premium.”');setReplies(['Add payments and analytics','Change timeline to 4 weeks','Change budget to £2,000']);input.placeholder='Tell me what to change…';input.focus({preventScroll:true});};
document.getElementById('copy').onclick=async()=>{await navigator.clipboard.writeText(briefText());toast('Project brief copied');};document.getElementById('download').onclick=()=>{const link=document.createElement('a');link.href=URL.createObjectURL(new Blob([briefText()],{type:'text/plain'}));link.download='briefbot-project-brief.txt';link.click();setTimeout(()=>URL.revokeObjectURL(link.href),0);toast('Brief downloaded');};document.getElementById('print').onclick=()=>window.print();
updateContext();start();
